numeros: 100000

sementes:
  - 123456

chegadas:
  F1: 2.0

filas:
  F1:
    servidores: 1
    capacidade: 5
    minChegada: 2.0
    maxChegada: 5.0
    minServico: 3.0
    maxServico: 5.0
  F2:
    servidores: 2
    capacidade: 3
#    minChegada: 2.0
#    maxChegada: 5.0
    minServico: 3.0
    maxServico: 5.0

rede:
  -  origem: F1
     destino: F2
     probabilidade: 1.0
